export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const USER_INFO = 'USER_INFO';

export const FETCH_SHOPPINGLISTS = 'FETCH_SHOPPINGLISTS';
export const FETCH_SHOPPINGLISTS_ERROR = 'FETCH_SHOPPINGLISTS_ERROR';

export const CREATE_SHOPPINGLIST = 'CREATE_SHOPPINGLIST';
export const CREATE_SHOPPINGLIST_ERROR = 'CREATE_SHOPPINGLIST_ERROR';

export const UPDATE_SHOPPINGLIST = 'UPDATE_SHOPPINGLIST';
export const UPDATE_SHOPPINGLIST_ERROR = 'UPDATE_SHOPPINGLIST_ERROR';

export const SHOPPINGLIST_DETAIL = 'SHOPPINGLIST_DETAIL';
export const SHOPPINGLIST_DETAIL_ERROR = 'SHOPPINGLIST_DETAIL_ERROR';

export const DELETE_SHOPPINGLIST = 'DELETE_SHOPPINGLIST';

export const CREATE_SHOPPING_ITEM = 'CREATE_SHOPPING_ITEM';
export const CREATE_SHOPPING_ITEM_ERROR = 'CREATE_SHOPPING_ITEM_ERROR';

export const FETCH_SHOPPING_ITEMS = 'FETCH_SHOPPING_ITEMS';
export const FETCH_SHOPPING_ITEMS_ERROR = 'FETCH_SHOPPING_ITEMS_ERROR';

export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SUCCESS_ALERT = 'SUCCESS_ALERT';
export const ERROR_ALERT = 'ERROR_ALERT';
export const WARNING_ALERT = 'WARNING_ALERT';